import mutations from "./mutations";
import actions from "./actions";
import getters from "./getters";

export default {
    namespaced: true,
    state() {
        return {
            id: 1,
            profile: {
                id: 1
            },
            created: '2020-09-17',
            list: [
                {
                    type: 'category',
                    name: 'spanie',
                    description: 'some text'
                },
                {
                    type: 'item',
                    name: 'śpiwór',
                    description: 'Lite Line 200',
                    weight: 510,
                    quantity: 1,
                    worn: false,
                    consumable: false,
                },
                {
                    type: 'item',
                    name: 'karimata',
                    description: 'Quechua m100',
                    weight: 200,
                    quantity: 1,
                    worn: false,
                    consumable: false,
                },
                {
                    type: 'item',
                    name: 'liner',
                    description: 'jedwabny decathlon',
                    weight: 110,
                    quantity: 1,
                    worn: false,
                    consumable: false,
                },
                {
                    type: 'item',
                    name: 'tarp',
                    description: 'Lesovik solo',
                    weight: 380,
                    quantity: 1,
                    worn: false,
                    consumable: false,
                },
                {
                    type: 'item',
                    name: 'sypialnia',
                    description: 'Simplex Mesh',
                    weight: 300,
                    quantity: 1,
                    worn: false,
                    consumable: false,
                },
                {
                    type: 'category',
                    name: 'gotowanie',
                    description: 'some text'
                },
                {
                    type: 'item',
                    name: 'kuchenka',
                    description: 'MSR Pocket Rocket 2',
                    weight: 74,
                    quantity: 1,
                    worn: false,
                    consumable: false,
                },
                {
                    type: 'item',
                    name: 'menażka',
                    description: 'decathlon 1l',
                    weight: 300,
                    quantity: 1,
                    worn: false,
                    consumable: false,
                },
                {
                    type: 'item',
                    name: 'gaz',
                    description: 'średni kartusz 230g gazu',
                    weight: 360,
                    quantity: 1,
                    worn: false,
                    consumable: true,
                },
                {
                    type: 'item',
                    name: 'łyżka i widelec',
                    description: 'decathlon',
                    weight: 10,
                    quantity: 1,
                    worn: false,
                    consumable: false,
                },
                {
                    type: 'category',
                    name: 'ubrania',
                    description: 'some text'
                },
                {
                    type: 'item',
                    name: 'polar',
                    description: 'regatta',
                    weight: 440,
                    quantity: 1,
                    worn: true,
                    consumable: false,
                },
                {
                    type: 'item',
                    name: 'koszulka',
                    description: 'decathlon poliester',
                    weight: 100,
                    quantity: 1,
                    worn: true,
                    consumable: false,
                },
                {
                    type: 'item',
                    name: 'skarpety',
                    description: 'merino',
                    weight: 50,
                    quantity: 3,
                    worn: true,
                    consumable: false,
                },
                {
                    type: 'item',
                    name: 'kurtka',
                    description: 'costabona',
                    weight: 120,
                    quantity: 3,
                    worn: false,
                    consumable: false,
                },
                {
                    type: 'item',
                    name: 'majtki',
                    description: 'merino',
                    weight: 65,
                    quantity: 2,
                    worn: true,
                    consumable: false,
                },
                {
                    type: 'item',
                    name: 'koszulka długa',
                    description: 'poliester',
                    weight: 170,
                    quantity: 1,
                    worn: false,
                    consumable: false,
                },
                {
                    type: 'item',
                    name: 'leginsy',
                    description: 'poliester',
                    weight: 170,
                    quantity: 1,
                    worn: false,
                    consumable: false,
                },
                {
                    type: 'item',
                    name: 'szorty',
                    description: 'czarne dectahlon',
                    weight: 120,
                    quantity: 1,
                    worn: true,
                    consumable: false,
                },
                {
                    type: 'item',
                    name: 'buff',
                    description: '',
                    weight: 40,
                    quantity: 1,
                    worn: true,
                    consumable: false,
                },
                {
                    type: 'item',
                    name: 'czapka z daszkiem',
                    description: 'SWE',
                    weight: 55,
                    quantity: 1,
                    worn: true,
                    consumable: false,
                },
                {
                    type: 'item',
                    name: 'czapka ciepła',
                    description: 'poliestrowa',
                    weight: 20,
                    quantity: 1,
                    worn: false,
                    consumable: false,
                },
                {
                    type: 'item',
                    name: 'peleryna plastikowa',
                    description: '',
                    weight: 70,
                    quantity: 1,
                    worn: false,
                    consumable: false,
                },
                {
                    type: 'item',
                    name: 'spodnie długie',
                    description: 'patagonia',
                    weight: 300,
                    quantity: 1,
                    worn: false,
                    consumable: false,
                },
                {
                    type: 'category',
                    name: 'higiena',
                    description: 'some text'
                },
                {
                    type: 'item',
                    name: 'pasta szczoteczka',
                    description: 'ajona i ucięta',
                    weight: 35,
                    quantity: 1,
                    worn: false,
                    consumable: false,
                },
                {
                    type: 'item',
                    name: 'mydło',
                    description: 'ziaja',
                    weight: 55,
                    quantity: 3,
                    worn: false,
                    consumable: true,
                },
                {
                    type: 'item',
                    name: 'papier',
                    description: '',
                    weight: 50,
                    quantity: 1,
                    worn: false,
                    consumable: true,
                },
                {
                    type: 'item',
                    name: 'pęsete',
                    description: 'na kleszcze',
                    weight: 5,
                    quantity: 1,
                    worn: false,
                    consumable: false,
                },
                {
                    type: 'category',
                    name: 'elektronika',
                    description: 'some text'
                },
                {
                    type: 'item',
                    name: 'tfon cegła',
                    description: 'samsung solid',
                    weight: 115,
                    quantity: 1,
                    worn: false,
                    consumable: false,
                },
                {
                    type: 'item',
                    name: 'smartphone',
                    description: 'iPhone 5',
                    weight: 110,
                    quantity: 1,
                    worn: false,
                    consumable: false,
                },
                {
                    type: 'item',
                    name: 'czołówka',
                    description: 'decathlon',
                    weight: 80,
                    quantity: 1,
                    worn: false,
                    consumable: false,
                },
                {
                    type: 'item',
                    name: 'zapasowe baterie',
                    description: '',
                    weight: 14,
                    quantity: 3,
                    worn: false,
                    consumable: false,
                },
                {
                    type: 'item',
                    name: 'ładowarki',
                    description: 'kostka + lightning + micro usb',
                    weight: 45,
                    quantity: 1,
                    worn: false,
                    consumable: false,
                },
                {
                    type: 'category',
                    name: 'inne',
                    description: 'some text'
                },
                {
                    type: 'item',
                    name: 'mapy',
                    description: '',
                    weight: 250,
                    quantity: 1,
                    worn: false,
                    consumable: false,
                },
                {
                    type: 'item',
                    name: 'nóż',
                    description: 'opinel',
                    weight: 15,
                    quantity: 1,
                    worn: false,
                    consumable: false,
                },
                {
                    type: 'item',
                    name: 'zapalniczka',
                    description: '',
                    weight: 15,
                    quantity: 1,
                    worn: false,
                    consumable: false,
                },
                {
                    type: 'item',
                    name: 'zestaw naprawczy',
                    description: '',
                    weight: 35,
                    quantity: 1,
                    worn: false,
                    consumable: false,
                },
                {
                    type: 'item',
                    name: 'apteczka',
                    description: '',
                    weight: 100,
                    quantity: 1,
                    worn: false,
                    consumable: false,
                },
                {
                    type: 'item',
                    name: 'portfel',
                    description: '',
                    weight: 100,
                    quantity: 1,
                    worn: false,
                    consumable: false,
                },
                {
                    type: 'item',
                    name: 'kije trekkingowe',
                    description: 'BD Ergo Cork z końcówkami gumowymi',
                    weight: 535,
                    quantity: 1,
                    worn: true,
                    consumable: false,
                },
                {
                    type: 'category',
                    name: 'plecaki i worki',
                    description: 'some text'
                },
                {
                    type: 'item',
                    name: 'plecak',
                    description: 'OnMyWay Triple Crown',
                    weight: 720,
                    quantity: 1,
                    worn: true,
                    consumable: false,
                },









            ]
        }
    },
    mutations,
    getters,
    actions
}